//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resort_Forest_Park.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Loginhistory
    {
        public int id_loginhistory { get; set; }
        public Nullable<int> id_employees { get; set; }
        public Nullable<System.DateTime> Lastentrance { get; set; }
        public string Logintype { get; set; }
    
        public virtual Employees Employees { get; set; }
    }
}
