//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resort_Forest_Park.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ForestEntities : DbContext
    {
        public ForestEntities()
            : base("name=ForestEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Client> Client { get; set; }
        public virtual DbSet<Employees> Employees { get; set; }
        public virtual DbSet<JobTitle> JobTitle { get; set; }
        public virtual DbSet<Loginhistory> Loginhistory { get; set; }
        public virtual DbSet<orderr> orderr { get; set; }
        public virtual DbSet<Service> Service { get; set; }
        public virtual DbSet<Servicee> Servicee { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
