//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resort_Forest_Park.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class orderr
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public orderr()
        {
            this.Servicee = new HashSet<Servicee>();
        }
    
        public int id_order { get; set; }
        public string Thecode { get; set; }
        public Nullable<System.DateTime> DateofCreation { get; set; }
        public string OrderTime { get; set; }
        public Nullable<int> id_client { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> Closingdate { get; set; }
        public string Rentaltime { get; set; }
        public Nullable<int> id_employee { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Employees Employees { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Servicee> Servicee { get; set; }
    }
}
